In [4]:
import numpy as np # 导入numpy
# 有几层括号代表几维
a = np.array([[1,2],[3,4]]) # 数组
a_m = np.matrix([[1,2],[3,4]]) # 矩阵
print(type(a))
print(type(a_m))
print(a)
print(a_m)
print(a*a) # 对应位置元素的乘积
print(a_m*a_m)# 矩阵相乘

<class 'numpy.ndarray'>
<class 'numpy.matrix'>
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [4]:
array1=([[]])
print(array1)

[[]]


In [208]:
for x in range(5):
    print(x)

0
1
2
3
4


In [209]:
# 列表生成式 [expression for item in range]
[x+1 for x in range(5)]

[1, 2, 3, 4, 5]

In [ ]:
a = [1,2]
b = [2,4]
c = a+b # 这样只能实现拼接，不能实现对应元素相加
c

[1, 2, 2, 4]

In [14]:
# 求两个数组对应元素相加
# python做法

def array_sum (n):
   a=[i+1 for i in range(n)]
   b=[i+1 for i in range(n)]
   new_list=[]
   for i in range(n):
         new_list.append(a[i]+b[i])
   return new_list

In [10]:
# numpy做法
def numpy_sum(n):
    a=np.arange(n)
    b=np.arange(n)
    a+=1
    b+=1
    return a+b

In [33]:
sum(5)

[2, 4, 6, 8, 10]

In [11]:
numpy_sum(5)

array([ 2,  4,  6,  8, 10])

In [ ]:

%timeit array_sum(5000)

819 μs ± 137 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [ ]:
# ± 1.36 μs(时间波动范围，以标准差衡量)
%timeit numpy_sum(5000)

10.8 μs ± 1.36 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


2024.11.12(学习到此)-----------------------------------------------------------------------------------------

In [2]:
import numpy as np
np.array
"""
object ： 数组序列
dtype：可选参数、通过它可以更改数组类型
copy：可选，当数据源为ndarray时表示数组能否被复制、默认为True
order：可选、以哪种内存布局来创建数组、分别为C(行序列)、F(列序列)、A(默认)
ndmin：可选、用于指定数组的维度
subok：可选、类型为bool、默认False。当为True时，使用object内部数据类型、为False时、使用数组数据类型
"""

'\nobject ： 数组序列\ndtype：可选参数、通过它可以更改数组类型\ncopy：可选，当数据源为ndarray时表示数组能否被复制、默认为True\norder：可选、以哪种内存布局来创建数组、分别为C(行序列)、F(列序列)、A(默认)\nndmin：可选、用于指定数组的维度\nsubok：可选、类型为bool、默认False。当为True时，使用object内部数据类型、为False时、使用数组数据类型\n'

In [6]:
import numpy as np # 创建一维数组
b = (np.array((1,2,3)))
print(b)
print(type(b))
print(type(np.array((1,2,3))))
a = np.array([1,2,3])
print(type(a))
a.ndim #维度 

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


1

In [2]:
import numpy as np # 创建二维数组
a = np.array([[1,2],[3,4]])
a.ndim

2

In [4]:
# 两种写法等价
a1= np.arange(10)
a2= np.array(range(10))
print(a1)
print(a2)
print(type(a1))
print(type(a2))



[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
# 不同类型,默认浮点
np.array([1,2,3,4.5])

array([1. , 2. , 3. , 4.5])

In [ ]:
np.array([1.2,2.3,3.4,4.5,5.6])
# 造成精度丢失
np.array([1.2,2.3,3.4,4.5,5.6],dtype=int)  # round(1.5) 

array([1, 2, 3, 4, 5])

In [ ]:
# 四舍五入
round(5.6)

6

In [ ]:
a = np.array([1,2,3])
print(a)
# 为什么a,b指向同一块地址？
# b并没有真正去复制一份 a 的数据到新的内存空间创建一个全新的数组，b 只是对原数组 a 的一种 “视图”（view）， b和a 共享同一块数内存地址，
# 它们只是在访问和操作这块共享数据上有不同的数组对象表现形式而已,类似于多个不同的变量名指向了同一个实际的对象.
b = np.array(a,copy=False) 
c = np.array(a,copy=True) 
print(b)
print(c)
print(id(a))
print(id(b))
print(id(c))

[1 2 3]
[1 2 3]
[1 2 3]
1623584230256
1623584230256
1623584143472


In [ ]:
# 对比上面代码
a = np.array([1,2,3])
c = a.copy()
print(id(a)) #1623558671888
print(id(c))
b = a    # b和a 指向同一块地址
print(id(b)) #1623558671888
d = np.array(a)
print(id(d))

1623558671888
1623558671792
1623558671888
1623558669680


In [6]:
a = np.array([1,2,3,4],ndmin=3)
a

array([[[1, 2, 3, 4]]])

In [62]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [ ]:
# 等差数列
a = np.linspace(1,10,10,dtype=int) 
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# 等比数列 ，base为底数
a = np.logspace(0,9,10,base=2) # 元素默认是浮点数类型 2^0~2~9
a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [ ]:
#按照 np.logspace 函数的计算逻辑，它会在以 10 为底的对数尺度上，均匀划分从起始对数 1 到终止对数 2 的范围，得到 10 个对数刻度值（在这个区间均匀分布），然后再通过以 10 为底的指数运算将这些对数刻度值转换为实际的等比数列元素值。
#具体计算过程如下：
#第一个元素：对应对数刻度值为起始值 1，实际值是 10 ** 1 = 10。
#第二个元素：计算出对应的对数刻度值（均匀划分区间得到），然后通过 10 为底的指数运算得到实际值，约为 12.91549665（计算方式是先算出均匀划分后的对数刻度值，再进行指数运算，即 10 ** (1 + (2 - 1) / 9)，这里 (2 - 1) / 9 是划分后的间隔，依次类推计算后续元素）。
#第三个元素：约为 16.68100537（计算为 10 ** (1 + 2 * (2 - 1) / 9)）。
#第四个元素：约为 21.5443469（计算为 10 ** (1 + 3 * (2 - 1) / 9)）。
#第五个元素：约为 27.82559402（计算为 10 ** (1 + 4 * (2 - 1) / 9)）。
#第六个元素：约为 35.93813664（计算为 10 ** (1 + 5 * (2 - 1) / 9)）。
#第七个元素：约为 46.41588834（计算为 10 ** (1 + 6 * (2 - 1) / 9)）。
#第八个元素：约为 59.94842503（计算为 10 ** (1 + 7 * (2 - 1) / 9)）。
#第九个元素：约为 77.42636827（计算为 10 ** (1 + 8 * (2 - 1) / 9)）。
#第十个元素：对应对数刻度值为终止值 2，实际值是 10 ** 2 = 100。
b = np.logspace(1,2,num=10) # base默认为10 1^10~10^10
b

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

2024.11.13(学习到此)-----------------------------------------------------------------------------------------

In [5]:
print(np.zeros(3))
print(np.zeros((2,3)))

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 最外层是一组中括号（对应第一个维度大小为 1），里面包含一组中括号（对应第二个维度大小为 2），
# 而这组中括号里的每个元素又是一组包含三个 1 的中括号（对应第三个维度大小为 3），
# 且元素的数据类型是 float（在 numpy 中，默认创建的数值类型为 float64，所以看到的是 1. 这种形式）
np.ones((1,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [234]:
# 数组属性
a = np.array([[1,2],[3,4]])
print(a)
a.shape

[[1 2]
 [3 4]]


(2, 2)

In [ ]:
a = np.arange(12)
print(a)
#reshape()创建一个新的数组视图，但数据与原数组 a 共享
#例如，如果原数组 a 有 12 个元素，那么可以将其重塑为 
#(3, 4)、(2, 6)、(1, 12) 等形状，
#但不能重塑为 (3, 5) 等元素数量不匹配的形状，否则会抛出异常。
a.reshape((3,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
#原数组 a 的形状会被直接修改为 (3, 5)。如果新形状的元素数量大于原数组，会在末尾填充新的值
a.resize((3,5),refcheck=False) # 默认以0填充
print(a)
a[2, 2:]=9 
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11  0  9  9]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11  9  9  9]]


In [244]:
# 维度
a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])
print(a.ndim)
print(b.ndim)
print(a.size)
print(b.size)

1
2
3
4


In [105]:
# 字节 8bit=1字节 int32 4字节
a = np.array([1,2,3,4])
print(a)
print(a.dtype)
a.itemsize

[1 2 3 4]
int32


4

In [110]:
# 索引和切片
a = np.array(range(10))
print(a[0])
print(a[1:5]) # 左闭右开
print(a[:])
print(a[1:-1:2])

0
[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]


In [117]:
a = np.arange(16).reshape(4,4)
print(a)
print(a[1])
print(a[2][2])
print(a[2:])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[4 5 6 7]
10
[[ 8  9 10 11]
 [12 13 14 15]]


In [121]:
a = np.arange(16).reshape(4,4)
print(a) 
print(a[...,1]) # 在行位置使用...,则代表选取所有行元素，反之则为所有列元素
print(a[...,1:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 1  5  9 13]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [245]:
a = np.arange(16).reshape(4,4)
print(a) 
a[...][1]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([4, 5, 6, 7])

In [15]:
a = np.arange(16).reshape(4,4)
print(a) 
print(a[0,2])
b = a[[0,1],[0,1]] # (0,0)和（1,1）位置元素
b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
2


array([0, 5])

In [127]:
# 布尔索引
a = np.arange(10)
a[a>5]

array([6, 7, 8, 9])

In [132]:
# 广播
a = np.arange(12).reshape(3,4)
print(a)
print(b)
b = np.array([1,2,3,4])
c = a+b
c

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 2 3 4]


array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11],
       [ 9, 11, 13, 15]])

In [260]:
# 求平均值
a = np.arange(12).reshape(3,4)
print(a)
a.mean(axis=0) # 列

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([4., 5., 6., 7.])

In [262]:
# 求最大值
a = np.arange(12).reshape(3,4)
print(a)
a.max(axis=0) # 列

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 8,  9, 10, 11])

In [263]:
b = np.array([1,2,3,4,5]) # 求中位数
np.median(b)

3.0

In [141]:
b = np.array([1,2,3,4,5])  # 标准差
np.std(b)

1.4142135623730951

In [153]:
# 随机数
np.random.rand(4,2)

array([[0.69596462, 0.15895499],
       [0.24303202, 0.73947226],
       [0.47200932, 0.31803411],
       [0.1614702 , 0.94418661]])

In [157]:
np.random.randn(4,2) # 具有标准正态分布的随机数 均值为0、标准差为1

array([[ 0.46425362, -0.6346284 ],
       [ 0.49483631,  0.29383029],
       [ 0.65112732,  1.56621523],
       [-2.27992794, -0.77440446]])

In [264]:
np.random.randint(-10,10,size=(2,2)) 

array([[-10,  -5],
       [ -5,   1]])

In [267]:
# 随机数种子
np.random.seed(21)
np.random.randn(4,2) 

array([[-0.05196425, -0.11119605],
       [ 1.0417968 , -1.25673929],
       [ 0.74538768, -1.71105376],
       [-0.20586438, -0.23457129]])

In [272]:
# 随机数种子
# np.random.seed(21)
np.random.randn(4,2) 

array([[-0.05196425, -0.11119605],
       [ 1.0417968 , -1.25673929],
       [ 0.74538768, -1.71105376],
       [-0.20586438, -0.23457129]])

In [247]:
# 添加
a = np.array([[1,2,3],[4,5,6]])
print(np.append(a,[7,8,9]))

[1 2 3 4 5 6 7 8 9]


In [16]:
# 添加
a = np.array([[1,2,3],[4,5,6]])
print(np.append(a,[[7,8,9]],axis=0)) # 添加在每列后面

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
a = np.array([[1,2,3],[4,5,6]])
print(np.append(a,[[7,8,9],[6,6,6]],axis=1))  # 添加在行后

[[1 2 3 7 8 9]
 [4 5 6 6 6 6]]


In [19]:
# 插入
a = np.array([1,2,3,4])
print(a)
np.insert(a,3,5)

[1 2 3 4]


array([1, 2, 3, 5, 4])

In [253]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(np.insert(a,1,6,axis=0)) # 行前进行插入
print(np.insert(a,1,6,axis=1)) # 列前进行插入

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [6 6 6]
 [4 5 6]]
[[1 6 2 3]
 [4 6 5 6]]


In [187]:
# 删除
a = np.arange(12).reshape(3,4)
print(a)
print(np.delete(a,1,axis=1)) #列
print(np.delete(a,1,axis=0)) # 行

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]


In [254]:
# 去重
a = np.array([1,2,3,4,4,4,5,6,7,7])
print(a)
uq = np.unique(a)
print(uq)

[1 2 3 4 4 4 5 6 7 7]
[1 2 3 4 5 6 7]


In [20]:
# 排序
a = np.array([[3,5,7],[4,1,10]])
print(a)
b = np.sort(a,axis=1) # 默认axis=1 按照行排序
b

[[ 3  5  7]
 [ 4  1 10]]


array([[ 3,  5,  7],
       [ 1,  4, 10]])

In [ ]:
import torch

# 创建一个形状为 [2, 3] 的张量（2行3列）
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x.shape)  # 输出: torch.Size([2, 3])

# 使用 view() 重塑为 [6]（一维向量）
y = x.view(6)
print(y.shape)  # 输出: torch.Size([6])
print(y)        # 输出: tensor([1, 2, 3, 4, 5, 6])

# -1展平并自动推断长度
z = x.view(-1)
print(z.shape)  # 输出: torch.Size([6])

torch.Size([2, 3])
torch.Size([6])
tensor([1, 2, 3, 4, 5, 6])
torch.Size([6])
