In [2]:
import torch
x = torch.arange(12)
print(x)
x1 = x.reshape(3,4)
x1
x2 = torch.tensor([[1.0, 2, 3], [4, 5, 6]])
x3 = torch.tensor([[1, 4, 2], [3, 1, 6]], dtype=torch.float32)
print(x2)
print(x3)
print(x2+x3)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 4., 2.],
        [3., 1., 6.]])
tensor([[ 2.,  6.,  5.],
        [ 7.,  6., 12.]])


### cat和stack拼接
cat指定拼接的维度

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6],])
print(x.shape)
y = torch.tensor([[1, 0, 1], [4, 0, 3]])
print()
print(y.shape)
z= torch.cat((x,y),dim=0) #按行拼接
print(f'z:{z} z shape: {z.shape}') 
f = torch.cat((x,y),dim=1) #按列拼接
print(f'f:{f} f shape: {f.shape}')
w = torch.stack((x,y),dim=0)
print(f'w:{w} w shape: {w.shape}')
f = torch.stack((x,y),dim=1)
print(f'f:{f} f shape: {f.shape}')



torch.Size([2, 3])

torch.Size([2, 3])
z:tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 0, 1],
        [4, 0, 3]]) z shape: torch.Size([4, 3])
f:tensor([[1, 2, 3, 1, 0, 1],
        [4, 5, 6, 4, 0, 3]]) f shape: torch.Size([2, 6])
w:tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 0, 1],
         [4, 0, 3]]]) w shape: torch.Size([2, 2, 3])
f:tensor([[[1, 2, 3],
         [1, 0, 1]],

        [[4, 5, 6],
         [4, 0, 3]]]) f shape: torch.Size([2, 2, 3])


In [ ]:
x == y

tensor([[ True, False, False],
        [ True, False, False]])

### 线性代数按轴求和
按哪个轴求和，哪个轴就拍扁变为0，该维度消失，如果keepdim=True，表示该维度不消失变为1

In [ ]:
x = torch.ones(2,1,4)
print(x)

print(x.sum(axis=0).shape)
print(x.sum(axis=1).shape)
print(x.sum(axis=2).shape)
print(x.sum(axis= [0,2]).shape)
print(x.sum(axis= [0,1],keepdim=True).shape)

tensor([[[1., 1., 1., 1.]],

        [[1., 1., 1., 1.]]])
torch.Size([1, 4])
torch.Size([2, 4])
torch.Size([2, 1])
torch.Size([1])
torch.Size([1, 1, 4])
