In [2]:
import torch

In [4]:
import torchvision

In [5]:
print(torch)

<module 'torch' from 'C:\\Users\\iyizuohz\\AppData\\Roaming\\Python\\Python312\\site-packages\\torch\\__init__.py'>


In [ ]:
# 创建一个张量包含两个元素
x=torch.tensor([5.5,3])
print(x)
x=x.new_ones(5,3,dtype=torch.double)
print(x)
new_x=torch.tensor([[1,2,3],[3,4,5]])
print(f'new_x={new_x}')
# 基于已有的张量创建一个二阶张量
x = torch.randn_like(x,dtype=torch.float)
print(x)
print(x.size())
# 二维张量的相加
y=torch.rand(5,3)
# 法一
print(x+y)
# 法二
print(torch.add(x,y))
# 提供tensor作为参数
result = torch.empty(5,3)
z=torch.add(x,y,out = result)
print(z)




tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
new_x=tensor([[1, 2, 3],
        [3, 4, 5]])
tensor([[ 0.4120,  0.7137, -0.2586],
        [ 0.1169,  0.3604, -0.2483],
        [-0.2630, -1.1450, -1.4426],
        [ 0.6650,  1.8293, -1.1649],
        [ 0.5603,  0.4311, -0.4894]])
torch.Size([5, 3])
tensor([[ 0.6751,  1.4423, -0.1069],
        [ 0.6364,  0.6722,  0.3179],
        [ 0.1833, -0.9052, -1.1655],
        [ 0.9714,  2.0395, -0.9702],
        [ 1.3119,  0.5636,  0.3902]])
tensor([[ 0.6751,  1.4423, -0.1069],
        [ 0.6364,  0.6722,  0.3179],
        [ 0.1833, -0.9052, -1.1655],
        [ 0.9714,  2.0395, -0.9702],
        [ 1.3119,  0.5636,  0.3902]])
tensor([[ 0.6751,  1.4423, -0.1069],
        [ 0.6364,  0.6722,  0.3179],
        [ 0.1833, -0.9052, -1.1655],
        [ 0.9714,  2.0395, -0.9702],
        [ 1.3119,  0.5636,  0.3902]])
tensor([ 0.7137,  0.3604, -1.1450, 

In [22]:
x=torch.tensor([[1,2,3],[3,4,5]])
print(x)
print(x[:, 1]) #选取所有行的第二列
print(x[0,2])
print(x[0,:])


tensor([[1, 2, 3],
        [3, 4, 5]])
tensor([2, 4])
tensor(3)
tensor([1, 2, 3])


# pytorch的自动微分

设置requires_grad=True 会跟踪张量的操作

    x ---> (x ** 2) ---> (2 * x) ---> (x ** 2 + 2 * x) ---> (x ** 2 + 2 * x + 1) = y

y.backward()：
调用 y 的 backward() 方法会触发梯度的计算。

PyTorch 会从 y 开始，根据计算图自动计算 y 关于 x 的梯度。

对于 y = x ** 2 + 2 * x + 1，其导数为 y' = 2x + 2。

当 x = 2.0 时，y' = 2 * 2 + 2 = 6.0。

In [ ]:
# 输入张量，并且设置 requires_grad=True
x = torch.tensor([2.0], requires_grad=True)
y = x ** 2 + 2 * x + 1

# 计算梯度,求导
y.backward()

# 获取梯度
print(x.grad)


tensor([6.])


In [33]:
x = torch.ones(2,2,requires_grad=True)
print(x)
y=x+1
print(y.grad_fn)     #grad_fn 是 y 张量的一个属性，它表示创建 y 张量的操作函数。
z = y*y*3
out = z.mean() #均值
print(z,out)
# 本身不返回值
print(out.backward())
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[12., 12.],
        [12., 12.]], grad_fn=<MulBackward0>) tensor(12., grad_fn=<MeanBackward0>)
None
tensor([[3., 3.],
        [3., 3.]])


View函数的使用

In [1]:
import torch

# 创建一个形状为 [2, 3] 的张量（2行3列）
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x.shape)  # 输出: torch.Size([2, 3])

# 使用 view() 重塑为 [6]（一维向量）
y = x.view(6)
print(y.shape)  # 输出: torch.Size([6])
print(y)        # 输出: tensor([1, 2, 3, 4, 5, 6])

# 等价于使用 -1 自动推断维度
z = x.view(-1)
print(z.shape)  # 输出: torch.Size([6])

torch.Size([2, 3])
torch.Size([6])
tensor([1, 2, 3, 4, 5, 6])
torch.Size([6])
